Website = "https://github.com/mauricext4fs/go-pomodoro"

[Details]
  Icon = "icon.png"
  Name = "Go Pomodoro"
  ID = "ch.mauricext4fs.gopomodoro"
  Version = "8.0.0"
  Build = 170

[LinuxAndBSD]
  GenericName = "Pomodoro"
  Categories = ["Productivity"]
  Comment = "Get more productive by using a counter to remind you to take a brake"
  Keywords = ["Pomodoro", "Counter"]
  ExecParams = "-x 42"
